---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GlobalTable MyApplication.
Parameters:
  GlobalTableName:
    Description: Name of the Global Table.
    Type: String
  GlobalTablePrimaryKey:
    Description: Primary key column name of the Global Table.
    Type: String
  LambdaRole:
    Description: IAM Role Arn to invoke DynamoDB from Lambda.
    Type: String

Resources:
  GlobalTableApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
          swagger: "2.0"
          info:
            version: "2016-12-09T04:29:17Z"
            title: MyGlobalApplication
          basePath: "/prod"
          schemes:
          - "https"
          paths:
            /SetDDB:
              get:
                consumes:
                - "application/json"
                produces:
                - "application/json"
                parameters: 
                - name: "key"
                  in: "query"
                  required: true
                  type: "string"
                - name: "value"
                  in: "query"
                  required: false
                  type: "string"
                responses:
                  "200":
                    description: "200 response"
                    schema:
                      $ref: "#/definitions/Empty"
                    headers:
                      Access-Control-Allow-Origin:
                        type: "string"
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: "200"
                      responseParameters:
                        method.response.header.Access-Control-Allow-Origin: "'*'"
                  uri:
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SetDDB.Arn}/invocations
                  passthroughBehavior: "when_no_templates"
                  httpMethod: "POST"
                  contentHandling: "CONVERT_TO_TEXT"
                  requestTemplates:
                    application/json:
                       "{\n    \"key\":  \"$input.params('key')\",\n    \"value\":  \"$input.params('value')\"  \n}"
                  type: "aws"
              options:
                consumes:
                - "application/json"
                produces:
                - "application/json"
                responses:
                  "200":
                    description: "200 response"
                    schema:
                      $ref: "#/definitions/Empty"
                    headers:
                      Access-Control-Allow-Origin:
                        type: "string"
                      Access-Control-Allow-Methods:
                        type: "string"
                      Access-Control-Allow-Headers:
                        type: "string"
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: "200"
                      responseParameters:
                        method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                        method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                        method.response.header.Access-Control-Allow-Origin: "'*'"
                  requestTemplates:
                    application/json: "{\"statusCode\": 200}"
                  passthroughBehavior: "when_no_match"
                  type: "mock"
            /GetDDB:
              get:
                consumes:
                - "application/json"
                produces:
                - "application/json"
                parameters: 
                - name: "key"
                  in: "query"
                  required: true
                  type: "string"
                responses:
                  "200":
                    description: "200 response"
                    schema:
                      $ref: "#/definitions/Empty"
                    headers:
                      Access-Control-Allow-Origin:
                        type: "string"
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: "200"
                      responseParameters:
                        method.response.header.Access-Control-Allow-Origin: "'*'"
                  uri:
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDDB.Arn}/invocations
                  passthroughBehavior: "when_no_templates"
                  httpMethod: "POST"
                  contentHandling: "CONVERT_TO_TEXT"
                  requestTemplates:
                    application/json:
                       "{\n    \"key\":  \"$input.params('key')\"  \n}"
                  type: "aws"
              options:
                consumes:
                - "application/json"
                produces:
                - "application/json"
                responses:
                  "200":
                    description: "200 response"
                    schema:
                      $ref: "#/definitions/Empty"
                    headers:
                      Access-Control-Allow-Origin:
                        type: "string"
                      Access-Control-Allow-Methods:
                        type: "string"
                      Access-Control-Allow-Headers:
                        type: "string"
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: "200"
                      responseParameters:
                        method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                        method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                        method.response.header.Access-Control-Allow-Origin: "'*'"
                  requestTemplates:
                    application/json: "{\"statusCode\": 200}"
                  passthroughBehavior: "when_no_match"
                  type: "mock"
            /healthcheckAPI:
              get:
                consumes:
                - "application/json"
                produces:
                - "application/json"
                responses:
                  "200":
                    description: "200 response"
                    schema:
                      $ref: "#/definitions/Empty"
                    headers:
                      Access-Control-Allow-Origin:
                        type: "string"
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: "200"
                      responseParameters:
                        method.response.header.Access-Control-Allow-Origin: "'*'"
                  uri:
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetHealthcheckAPI.Arn}/invocations
                  passthroughBehavior: "when_no_templates"
                  httpMethod: "POST"
                  contentHandling: "CONVERT_TO_TEXT"
                  type: "aws"
              options:
                consumes:
                - "application/json"
                produces:
                - "application/json"
                responses:
                  "200":
                    description: "200 response"
                    schema:
                      $ref: "#/definitions/Empty"
                    headers:
                      Access-Control-Allow-Origin:
                        type: "string"
                      Access-Control-Allow-Methods:
                        type: "string"
                      Access-Control-Allow-Headers:
                        type: "string"
                x-amazon-apigateway-integration:
                  responses:
                    default:
                      statusCode: "200"
                      responseParameters:
                        method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                        method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                        method.response.header.Access-Control-Allow-Origin: "'*'"
                  requestTemplates:
                    application/json: "{\"statusCode\": 200}"
                  passthroughBehavior: "when_no_match"
                  type: "mock"
          definitions:
            Empty:
              type: "object"
              title: "Empty Schema"


  SetDDB:
    Type: AWS::Serverless::Function
    Properties:
      Role: !Ref LambdaRole
      CodeUri: .
      Handler: setDDB.lambda_handler
      Runtime: python2.7
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
          TABLE: !Ref GlobalTableName
          KeyCol: !Ref GlobalTablePrimaryKey
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref GlobalTableApi
            Path: /SetDDB
            Method: get


  GetDDB:
    Type: AWS::Serverless::Function
    Properties:
      Role: !Ref LambdaRole  
      CodeUri: .
      Handler: getDDB.lambda_handler
      Runtime: python2.7
      Environment:
        Variables:
          REGION: !Ref "AWS::Region"
          TABLE: !Ref GlobalTableName
          KeyCol: !Ref GlobalTablePrimaryKey
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref GlobalTableApi
            Path: /GetDDB
            Method: get


  GetHealthcheckAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: get_healthcheck.lambda_handler
      Runtime: python2.7
      Environment:
        Variables:
          STATUS: "ok"
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref GlobalTableApi
            Path: /healthcheckAPI
            Method: get


Outputs:
  RestAPIID:
    Description: Rest API ID
    Value: !Ref GlobalTableApi
  SetDDBApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref GlobalTableApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/prod'
  GetDDBApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref GlobalTableApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/prod'
